import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-black antialiased`}
      >
        <header className="fixed top-0 w-full z-50">
          <div className="bg-black flex items-center justify-between h-full px-3">
            <div className="flex items-center gap-2">
              <div className="bg-gradient-to-r from-violet-500 to-fuchsia-500 bg-clip-text text-2xl font-bold text-transparent">
                My App
              </div>
            </div>
            <nav className="flex item-center gap-4">
              <a className="text-gray-400 hover:text-orange-600 font-bold">
                Home
              </a>
              <a href="/about" className="text-gray-400 hover:text-orange-600 font-bold">
                About
              </a>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
